[test]
preload = ["./src/test/setup.ts"]
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coveragePathIgnorePatterns = [
  "dist/**",
  "**/test/**",
  "**/*.gen.ts",
  "**/routeTree.gen.ts",
]
