[test]
root = "src"
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
# Disabling threshold until catalog coverage improved
# coverageThreshold = { lines = 0.30, functions = 0.30 }
coveragePathIgnorePatterns = [
  "dist/**",
  "**/test/**",
  "**/*.gen.ts",
  "../../packages/**",
]
